<?php namespace ProcessWire;
/* 
Process Server Assert.
This script contains code available in the install.php
of ProcessWire.

MIT License

Copyright (c) 2016 Camilo Castro - Ninjas.cl

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

require_once dirname(__FILE__) . '/ServerAssert.php';
use \ServerAssert\ServerAssert as ServerAssert;

class ProcessServerAssert extends Process implements Module {

	public static function getModuleInfo() {
		return  [
			'title' => 'Server Assert',
			'summary' => __('Simple Module for Asserting if the server pass the minimum requirements for Processwire.'),
			'version' => 101,
			'author' => 'Ninjas.cl',
			'singular' => true,
			'href' => 'https://github.com/NinjasCL/ProcessServerAssert'
		];
	}

	public function install() {

			$page = new Page();
			$page->template = 'admin';
			$page->name = 'njs-server-assert';
			$page->title = 'Server Assert';
			$page->save();

			$page->process = 'ProcessServerAssert';
			$admin = $this->pages->get($this->config->adminRootPageID);
			$page->parent = $admin;

			$page->save();
	}

	public function uninstall() {
		
		$page = $this->pages->get('name=njs-server-assert');

		if($page instanceof Page) {
			$this->pages->delete($page, true);	
		} 
	}

	public function execute() {

		// Assert with the path to root
		$data = ServerAssert::assert('../../');

		foreach ($data['messages'] as $text) {
			$this->message($text);
		}

		foreach ($data['errors'] as $text) {
			$this->error($text);
		}

		foreach ($data['warnings'] as $text) {
			$this->warning($text);
		}

		return $data['stats'];
	}
}